import * as React from "react";
import {
  ScrollView,
  Image,
  StyleSheet,
  Pressable,
  Text,
  View,
} from "react-native";
import { StackNavigationProp } from "@react-navigation/stack";
import { useNavigation, ParamListBase } from "@react-navigation/native";
import CognitiveReframingHeader from "../components/CognitiveReframingHeader";
import { Border, FontFamily, FontSize, Color } from "../GlobalStyles";

const CognitiveReframingWithInput = () => {
  const navigation = useNavigation<StackNavigationProp<ParamListBase>>();

  return (
    <ScrollView style={styles.cognitiveReframingWithInput}>
      <Image
        style={styles.nicePatternForStepsPage}
        resizeMode="cover"
        source={require("../assets/nice-pattern-for-steps-page.png")}
      />
      <Pressable
        style={styles.naledi31}
        onPress={() => navigation.navigate("CognitiveReframingLoading")}
      >
        <Image
          style={styles.icon}
          resizeMode="cover"
          source={require("../assets/naledi-3-1.png")}
        />
      </Pressable>
      <View style={[styles.inputField, styles.inputFieldLayout]}>
        <Text style={styles.inputThoughtHere}>Input thought here</Text>
      </View>
      <Image
        style={[styles.sendButtonIcon, styles.inputFieldLayout]}
        resizeMode="cover"
        source={require("../assets/send-button.png")}
      />
      <View
        style={[styles.usersInputShouldAppearHerWrapper, styles.wrapperLayout]}
      >
        <Text
          style={[styles.usersInputShould, styles.usersInputShouldTypo]}
        >{`User\`s Input Should Appear here after being entered. There should a be a word limit so that they fit inside this container `}</Text>
      </View>
      <View
        style={[
          styles.theReframedPerpectiveGeneraWrapper,
          styles.wrapperLayout,
        ]}
      >
        <Text
          style={[styles.theReframedPerpective, styles.usersInputShouldTypo]}
        >{`The reframed perpective generated by AI is then displayed here. `}</Text>
      </View>
      <Text style={[styles.yourThought, styles.yourThoughtTypo]}>
        Your Thought
      </Text>
      <Text style={[styles.reframedPerspective, styles.yourThoughtTypo]}>
        Reframed Perspective
      </Text>
      <CognitiveReframingHeader />
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  inputFieldLayout: {
    overflow: "hidden",
    height: 66,
    borderRadius: Border.br_2xs,
    top: 814,
    position: "absolute",
  },
  wrapperLayout: {
    height: 123,
    width: 391,
    left: 19,
    borderRadius: Border.br_2xs,
    position: "absolute",
  },
  usersInputShouldTypo: {
    height: 91,
    width: 330,
    fontFamily: FontFamily.poppinsMedium,
    fontWeight: "500",
    fontSize: FontSize.size_base,
    top: 11,
    textAlign: "center",
    lineHeight: 34,
    left: "50%",
    position: "absolute",
  },
  yourThoughtTypo: {
    textAlign: "left",
    fontSize: FontSize.size_xl,
    color: Color.pRIMARYFONT,
    fontFamily: FontFamily.poppinsSemiBold,
    fontWeight: "600",
    lineHeight: 34,
    left: "50%",
    top: "50%",
    position: "absolute",
  },
  nicePatternForStepsPage: {
    top: 116,
    left: -37,
    width: 500,
    height: 526,
    position: "absolute",
  },
  icon: {
    height: "100%",
    width: "100%",
  },
  naledi31: {
    left: 105,
    top: 143,
    width: 196,
    height: 177,
    position: "absolute",
  },
  inputThoughtHere: {
    marginTop: -17,
    marginLeft: -129,
    fontSize: FontSize.size_mini,
    width: 205,
    textAlign: "center",
    fontFamily: FontFamily.poppinsSemiBold,
    fontWeight: "600",
    lineHeight: 34,
    left: "50%",
    top: "50%",
    color: Color.pRIMARYFONT,
    position: "absolute",
  },
  inputField: {
    left: 28,
    width: 298,
    backgroundColor: Color.white,
  },
  sendButtonIcon: {
    left: 338,
    width: 72,
  },
  usersInputShould: {
    marginLeft: -164.5,
    color: Color.pRIMARYFONT,
    height: 91,
    width: 330,
    fontFamily: FontFamily.poppinsMedium,
    fontWeight: "500",
    fontSize: FontSize.size_base,
    top: 11,
  },
  usersInputShouldAppearHerWrapper: {
    top: 380,
    borderStyle: "solid",
    borderColor: Color.bTCDARKGREEN,
    borderWidth: 3,
    backgroundColor: Color.white,
  },
  theReframedPerpective: {
    marginLeft: -153.5,
    color: Color.bTCWHITE,
  },
  theReframedPerpectiveGeneraWrapper: {
    top: 559,
    backgroundColor: Color.bTCDARKGREEN,
  },
  yourThought: {
    marginTop: -124.5,
    marginLeft: -75,
    width: 142,
  },
  reframedPerspective: {
    marginTop: 53.5,
    marginLeft: -113,
    width: 227,
  },
  cognitiveReframingWithInput: {
    backgroundColor: Color.cREAMWHITE,
    flex: 1,
    maxWidth: "100%",
    width: "100%",
  },
});

export default CognitiveReframingWithInput;
